1aaabbcccdddee02-H
exampleuser 1168 982
<exampleuser@cpanel.example.test>
1777409086 0
-received_time_usec .296607
-body_linecount 18
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
target@example.org

233P Received: from exampleuser by cpanel.example.test
028  Subject: Free deal inside
132  X-PHP-Script: hijacked.example.com/wp-content/plugins/x.php for 192.0.2.11
038  Date: Tue, 28 Apr 2026 20:45:00 +0000
047F From: Naked <attacker@spoofed.example>
067  X-Mailer: PHPMailer 6.5.0 (https://github.com/PHPMailer/PHPMailer)
018  MIME-Version: 1.0
039  Content-Type: text/html; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
