1aaabbcccdddee01-H
exampleuser 1168 982
<exampleuser@cpanel.example.test>
1777409086 0
-received_time_usec .296607
-body_linecount 21
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
info@example.com

233P Received: from exampleuser by cpanel.example.test
037  Subject: New message from realvision
132  X-PHP-Script: rentvsloan.example.com/wp-admin/admin-ajax.php for 192.0.2.10
038  Date: Tue, 28 Apr 2026 20:44:46 +0000
048F From: Spoof <attacker@spoofed.example>
031R Reply-To: attacker@gmail.example
067  X-Mailer: PHPMailer 7.0.0 (https://github.com/PHPMailer/PHPMailer)
018  MIME-Version: 1.0
039  Content-Type: text/html; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
