1aaabbcccdddee07-H
exampleuser 1168 982
<exampleuser@cpanel.example.test>
1777409086 0
-received_time_usec .296607
-body_linecount 22
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
inquiries@example.com

233P Received: from exampleuser by cpanel.example.test
038  Subject: New contact form submission
132  X-PHP-Script: example.com/wp-admin/admin-ajax.php for 192.0.2.15
038  Date: Tue, 28 Apr 2026 20:50:00 +0000
041F From: Site <site@example.com>
035R Reply-To: visitor@gmail.example
067  X-Mailer: PHPMailer 7.0.0 (https://github.com/PHPMailer/PHPMailer)
018  MIME-Version: 1.0
039  Content-Type: text/html; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
