1aaabbcccdddee05-H
exampleuser 1168 982
<exampleuser@cpanel.example.test>
1777409086 0
-received_time_usec .296607
-body_linecount 9
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
exampleuser@example.com

233P Received: from exampleuser by cpanel.example.test
037  Subject: cPanel server status update
132  X-PHP-Script: cpanel.example.test/cpanel/notify.php for 192.0.2.14
038  Date: Tue, 28 Apr 2026 20:48:00 +0000
037F From: cPanel <cPanel@example.com>
036  X-Mailer: cPanel (cpsrvd-cpanel)
018  MIME-Version: 1.0
036  Content-Type: text/plain; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
