1aaabbcccdddee03-H
exampleuser 1168 982
<exampleuser@cpanel.example.test>
1777409086 0
-received_time_usec .296607
-body_linecount 32
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
customer@example.org

233P Received: from exampleuser by cpanel.example.test
038  Subject: Your order #14523 is confirmed
132  X-PHP-Script: shop.example.com/wp-content/plugins/woocommerce/wc-emails.php for 192.0.2.12
038  Date: Tue, 28 Apr 2026 20:46:00 +0000
037F From: Shop <shop@example.com>
060  X-Mailer: WooCommerce 8.4.0 (cPanel.example.com)
018  MIME-Version: 1.0
039  Content-Type: text/html; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
