1aaabbcccdddee06-H
exampleuser 1168 982
<bounce@mc.example.org>
1777409086 0
-received_time_usec .296607
-body_linecount 28
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
exampleuser@example.com

233P Received: from mailchimp by cpanel.example.test
037  Subject: Your weekly newsletter
038  Date: Tue, 28 Apr 2026 20:49:00 +0000
047F From: Newsletter <news@mc.example.org>
050  X-Mailer: MailChimp Mailer - **CID0123abcd**
018  MIME-Version: 1.0
039  Content-Type: text/html; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
