1aaabbcccdddee04-H
exampleuser 1168 982
<exampleuser@cpanel.example.test>
1777409086 0
-received_time_usec .296607
-body_linecount 14
-allow_unqualified_recipient
-allow_unqualified_sender
-local
1
admin@example.com

233P Received: from exampleuser by cpanel.example.test
041  Subject: [Site] New comment awaiting review
132  X-PHP-Script: blog.example.com/wp-includes/pluggable.php for 192.0.2.13
038  Date: Tue, 28 Apr 2026 20:47:00 +0000
049F From: WordPress <wordpress@example.com>
050  X-Mailer: WordPress/6.4.3; https://blog.example.com
018  MIME-Version: 1.0
036  Content-Type: text/plain; charset=UTF-8
032  Content-Transfer-Encoding: 8bit
