// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package sensitive_file_bpfprog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SensitiveFileFileid struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type SensitiveFileSensitiveEvent struct {
	_    structs.HostLayout
	Uid  uint32
	Pid  uint32
	Mask uint32
	_    [4]byte
	Dev  uint64
	Ino  uint64
	Comm [16]uint8
}

// LoadSensitiveFile returns the embedded CollectionSpec for SensitiveFile.
func LoadSensitiveFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SensitiveFileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SensitiveFile: %w", err)
	}

	return spec, err
}

// LoadSensitiveFileObjects loads SensitiveFile and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SensitiveFileObjects
//	*SensitiveFilePrograms
//	*SensitiveFileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSensitiveFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSensitiveFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SensitiveFileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SensitiveFileSpecs struct {
	SensitiveFileProgramSpecs
	SensitiveFileMapSpecs
	SensitiveFileVariableSpecs
}

// SensitiveFileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SensitiveFileProgramSpecs struct {
	CsmFilePerm *ebpf.ProgramSpec `ebpf:"csm_file_perm"`
}

// SensitiveFileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SensitiveFileMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	Watched *ebpf.MapSpec `ebpf:"watched"`
}

// SensitiveFileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SensitiveFileVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// SensitiveFileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSensitiveFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type SensitiveFileObjects struct {
	SensitiveFilePrograms
	SensitiveFileMaps
	SensitiveFileVariables
}

func (o *SensitiveFileObjects) Close() error {
	return _SensitiveFileClose(
		&o.SensitiveFilePrograms,
		&o.SensitiveFileMaps,
	)
}

// SensitiveFileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSensitiveFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type SensitiveFileMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	Watched *ebpf.Map `ebpf:"watched"`
}

func (m *SensitiveFileMaps) Close() error {
	return _SensitiveFileClose(
		m.Events,
		m.Watched,
	)
}

// SensitiveFileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSensitiveFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type SensitiveFileVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// SensitiveFilePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSensitiveFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type SensitiveFilePrograms struct {
	CsmFilePerm *ebpf.Program `ebpf:"csm_file_perm"`
}

func (p *SensitiveFilePrograms) Close() error {
	return _SensitiveFileClose(
		p.CsmFilePerm,
	)
}

func _SensitiveFileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sensitivefile_arm64_bpfel.o
var _SensitiveFileBytes []byte
