// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package af_alg_bpfprog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AFAlgAfAlgEvent struct {
	_          structs.HostLayout
	Uid        uint32
	Pid        uint32
	Ppid       uint32
	Comm       [16]uint8
	ParentComm [16]uint8
	Exe        [256]uint8
}

type AFAlgCsmQueueStats struct {
	_         structs.HostLayout
	Lost      uint64
	Submitted uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	AFAlgMapEvents         = "events"
	AFAlgMapQueueStats     = "queue_stats"
	AFAlgProgCsmBlockAfAlg = "csm_block_af_alg"
	AFAlgVarUnused         = "unused"
)

// LoadAFAlg returns the embedded CollectionSpec for AFAlg.
func LoadAFAlg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AFAlgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load AFAlg: %w", err)
	}

	return spec, err
}

// LoadAFAlgObjects loads AFAlg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AFAlgObjects
//	*AFAlgPrograms
//	*AFAlgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAFAlgObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAFAlg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AFAlgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AFAlgSpecs struct {
	AFAlgProgramSpecs
	AFAlgMapSpecs
	AFAlgVariableSpecs
}

// AFAlgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AFAlgProgramSpecs struct {
	CsmBlockAfAlg *ebpf.ProgramSpec `ebpf:"csm_block_af_alg"`
}

// AFAlgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AFAlgMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	QueueStats *ebpf.MapSpec `ebpf:"queue_stats"`
}

// AFAlgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AFAlgVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// AFAlgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAFAlgObjects or ebpf.CollectionSpec.LoadAndAssign.
type AFAlgObjects struct {
	AFAlgPrograms
	AFAlgMaps
	AFAlgVariables
}

func (o *AFAlgObjects) Close() error {
	return _AFAlgClose(
		&o.AFAlgPrograms,
		&o.AFAlgMaps,
	)
}

// AFAlgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAFAlgObjects or ebpf.CollectionSpec.LoadAndAssign.
type AFAlgMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	QueueStats *ebpf.Map `ebpf:"queue_stats"`
}

func (m *AFAlgMaps) Close() error {
	return _AFAlgClose(
		m.Events,
		m.QueueStats,
	)
}

// AFAlgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAFAlgObjects or ebpf.CollectionSpec.LoadAndAssign.
type AFAlgVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// AFAlgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAFAlgObjects or ebpf.CollectionSpec.LoadAndAssign.
type AFAlgPrograms struct {
	CsmBlockAfAlg *ebpf.Program `ebpf:"csm_block_af_alg"`
}

func (p *AFAlgPrograms) Close() error {
	return _AFAlgClose(
		p.CsmBlockAfAlg,
	)
}

func _AFAlgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed afalg_x86_bpfel.o
var _AFAlgBytes []byte
