package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"syscall"
	"time"

	systemdbus "github.com/coreos/go-systemd/v22/dbus"
	"github.com/pidginhost/csm/internal/config"
	"github.com/pidginhost/csm/internal/platform"
)

func runSystemdRoots() {
	cfg := loadConfigLite()
	content, err := systemdAccountRootsDropIn(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Cannot generate account-root grants: %v\n", err)
		os.Exit(1)
	}
	fmt.Print(content)
}

func systemdAccountRootsDropIn(cfg *config.Config) (string, error) {
	roots, err := serviceAccountContentRoots(cfg, true)
	if err != nil {
		return "", err
	}
	if len(roots) == 0 {
		return "", fmt.Errorf("no existing account directories; provision them before generating grants")
	}
	var grants []string
	for _, root := range roots {
		grant, err := trustedServiceGrant(root)
		if err != nil {
			return "", err
		}
		grants = append(grants, grant)
	}
	slices.Sort(grants)
	var compact []string
	for _, grant := range grants {
		if len(compact) == 0 || !servicePathWithin(grant, compact[len(compact)-1]) {
			compact = append(compact, grant)
		}
	}
	var unit strings.Builder
	unit.WriteString("# Generated by csm systemd-roots; regenerate after changing account roots.\n[Unit]\n")
	for _, grant := range compact {
		fmt.Fprintf(&unit, "RequiresMountsFor=%s\n", quoteSystemdPath(grant))
	}
	unit.WriteString("\n[Service]\n")
	for _, grant := range compact {
		fmt.Fprintf(&unit, "ReadWritePaths=%s\n", quoteSystemdPath(grant))
	}
	return unit.String(), nil
}

func quoteSystemdPath(path string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "%", "%%").Replace(path) + `"`
}

func servicePathWithin(path, root string) bool {
	return path == root || strings.HasPrefix(path, strings.TrimSuffix(root, "/")+"/")
}

// A tenant can replace a directory it owns with a symlink before systemd
// starts. Grant the nearest ancestor whose name and contents root controls;
// never turn that search into a write grant for a whole system directory.
func trustedServiceGrant(path string) (string, error) {
	current, trusted := "/", ""
	for _, part := range strings.Split(strings.TrimPrefix(path, "/"), "/") {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if err != nil {
			return "", err
		}
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("service grant ancestor must be a real directory: %s", current)
		}
		stat := info.Sys().(*syscall.Stat_t)
		if stat.Uid != 0 {
			break
		}
		if info.Mode().Perm()&0022 != 0 {
			// A root-owned child of a root-owned sticky directory cannot be
			// renamed by other users. The sticky directory itself is no grant.
			if info.Mode()&os.ModeSticky != 0 {
				continue
			}
			break
		}
		trusted = current
	}
	if trusted == "" || (filepath.Dir(trusted) == "/" && trusted != "/home") {
		return "", fmt.Errorf("no narrow root-owned service grant for %s; place accounts beneath a root-owned directory such as /srv/csm-accounts", path)
	}
	return trusted, nil
}

func serviceAccountContentRoots(cfg *config.Config, includeDefaultHome bool) ([]string, error) {
	var patterns []string
	if cfg != nil {
		patterns = cfg.AccountRoots
	}
	roots, err := platform.ResolveAccountRoots(patterns)
	if err != nil {
		return nil, err
	}
	if len(patterns) > 0 && len(roots) == 0 {
		return nil, fmt.Errorf("configured account roots match no existing content directories")
	}
	for _, root := range platform.Detect().AccountHomeRoots() {
		if root == "/home" && !includeDefaultHome {
			continue
		}
		info, err := os.Lstat(root)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return nil, err
		}
		if !info.IsDir() {
			return nil, fmt.Errorf("platform account root is not a real directory: %s", root)
		}
		roots = append(roots, root)
	}
	return roots, nil
}

type accountServiceAccess struct {
	WritePaths    []string
	ProtectSystem string
	MainPID       uint32
}

var readAccountServiceAccess = func() (accountServiceAccess, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	conn, err := systemdbus.NewSystemdConnectionContext(ctx)
	if err != nil {
		return accountServiceAccess{}, err
	}
	defer conn.Close()
	properties, err := conn.GetUnitTypePropertiesContext(ctx, "csm.service", "Service")
	if err != nil {
		return accountServiceAccess{}, err
	}
	paths, pathsOK := properties["ReadWritePaths"].([]string)
	protection, protectionOK := properties["ProtectSystem"].(string)
	pid, pidOK := properties["MainPID"].(uint32)
	if !pathsOK || !protectionOK || !pidOK {
		return accountServiceAccess{}, fmt.Errorf("systemd omitted account-root access properties")
	}
	return accountServiceAccess{WritePaths: paths, ProtectSystem: protection, MainPID: pid}, nil
}

var accountServiceRootWritable = serviceRootWritable

func doctorAccountRootAccess(cfg *config.Config) []DoctorCheck {
	roots, err := serviceAccountContentRoots(cfg, false)
	if err == nil && len(roots) == 0 {
		return nil
	}
	check := DoctorCheck{Name: "account root access", Status: "fail", Fix: "generate and install the csm systemd-roots drop-in, then run systemctl daemon-reload and restart csm.service; see the custom account roots guide"}
	if err != nil {
		check.Message = err.Error()
		return []DoctorCheck{check}
	}
	access, err := readAccountServiceAccess()
	if err != nil {
		check.Status, check.Message = "warn", "cannot inspect csm.service write access: "+err.Error()
		return []DoctorCheck{check}
	}
	for _, root := range roots {
		covered := false
		for _, grant := range access.WritePaths {
			if servicePathWithin(root, strings.TrimPrefix(grant, "-")) {
				covered = true
				break
			}
		}
		if access.ProtectSystem == "strict" && !covered {
			check.Message = "service has no write grant for " + root
			return []DoctorCheck{check}
		}
		if access.MainPID != 0 {
			writable, err := accountServiceRootWritable(access.MainPID, root)
			if err != nil {
				check.Message = fmt.Sprintf("cannot inspect live service root %s: %v", root, err)
				return []DoctorCheck{check}
			}
			if !writable {
				check.Message = "account root is read-only in the running service: " + root
				return []DoctorCheck{check}
			}
		}
	}
	check.Status, check.Message, check.Fix = "ok", "configured content roots are writable in the running service", ""
	if access.MainPID == 0 {
		check.Status, check.Message = "warn", "configured grants cover account roots; start the service to verify its mount access"
		check.Fix = "start csm.service and run csm doctor again"
	} else if access.ProtectSystem != "strict" {
		check.Status, check.Message = "warn", "account roots are writable, but csm.service does not use ProtectSystem=strict"
		check.Fix = "restore the packaged service sandbox and use narrow account-root grants"
	}
	return []DoctorCheck{check}
}
