// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package connection_bpfprog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ConnectionConnEvent struct {
	_        structs.HostLayout
	Uid      uint32
	Pid      uint32
	Family   uint32
	DstPort  uint32
	DstIp4   uint32
	DstIp6   [16]uint8
	Comm     [16]uint8
	Decision uint32
}

type ConnectionPolicyState struct {
	_              structs.HostLayout
	Enforce        uint32
	DryRun         uint32
	ProtectedPorts uint32
}

// LoadConnection returns the embedded CollectionSpec for Connection.
func LoadConnection() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectionBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Connection: %w", err)
	}

	return spec, err
}

// LoadConnectionObjects loads Connection and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ConnectionObjects
//	*ConnectionPrograms
//	*ConnectionMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadConnectionObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadConnection()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ConnectionSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionSpecs struct {
	ConnectionProgramSpecs
	ConnectionMapSpecs
	ConnectionVariableSpecs
}

// ConnectionProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionProgramSpecs struct {
	CsmConnect4 *ebpf.ProgramSpec `ebpf:"csm_connect4"`
	CsmConnect6 *ebpf.ProgramSpec `ebpf:"csm_connect6"`
}

// ConnectionMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	Policy         *ebpf.MapSpec `ebpf:"policy"`
	ProtectedPorts *ebpf.MapSpec `ebpf:"protected_ports"`
	SafeUids       *ebpf.MapSpec `ebpf:"safe_uids"`
}

// ConnectionVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ConnectionVariableSpecs struct {
	Unused       *ebpf.VariableSpec `ebpf:"unused"`
	UnusedPolicy *ebpf.VariableSpec `ebpf:"unused_policy"`
}

// ConnectionObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionObjects struct {
	ConnectionPrograms
	ConnectionMaps
	ConnectionVariables
}

func (o *ConnectionObjects) Close() error {
	return _ConnectionClose(
		&o.ConnectionPrograms,
		&o.ConnectionMaps,
	)
}

// ConnectionMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	Policy         *ebpf.Map `ebpf:"policy"`
	ProtectedPorts *ebpf.Map `ebpf:"protected_ports"`
	SafeUids       *ebpf.Map `ebpf:"safe_uids"`
}

func (m *ConnectionMaps) Close() error {
	return _ConnectionClose(
		m.Events,
		m.Policy,
		m.ProtectedPorts,
		m.SafeUids,
	)
}

// ConnectionVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionVariables struct {
	Unused       *ebpf.Variable `ebpf:"unused"`
	UnusedPolicy *ebpf.Variable `ebpf:"unused_policy"`
}

// ConnectionPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadConnectionObjects or ebpf.CollectionSpec.LoadAndAssign.
type ConnectionPrograms struct {
	CsmConnect4 *ebpf.Program `ebpf:"csm_connect4"`
	CsmConnect6 *ebpf.Program `ebpf:"csm_connect6"`
}

func (p *ConnectionPrograms) Close() error {
	return _ConnectionClose(
		p.CsmConnect4,
		p.CsmConnect6,
	)
}

func _ConnectionClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connection_arm64_bpfel.o
var _ConnectionBytes []byte
