// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package exec_bpfprog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ExecExecEvent struct {
	_          structs.HostLayout
	Uid        uint32
	Pid        uint32
	Ppid       uint32
	Comm       [16]uint8
	ParentComm [16]uint8
	Filename   [256]uint8
}

// LoadExec returns the embedded CollectionSpec for Exec.
func LoadExec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Exec: %w", err)
	}

	return spec, err
}

// LoadExecObjects loads Exec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecObjects
//	*ExecPrograms
//	*ExecMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecSpecs struct {
	ExecProgramSpecs
	ExecMapSpecs
	ExecVariableSpecs
}

// ExecProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecProgramSpecs struct {
	CsmOnExec *ebpf.ProgramSpec `ebpf:"csm_on_exec"`
}

// ExecMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ExecVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// ExecObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecObjects struct {
	ExecPrograms
	ExecMaps
	ExecVariables
}

func (o *ExecObjects) Close() error {
	return _ExecClose(
		&o.ExecPrograms,
		&o.ExecMaps,
	)
}

// ExecMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ExecMaps) Close() error {
	return _ExecClose(
		m.Events,
	)
}

// ExecVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// ExecPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecPrograms struct {
	CsmOnExec *ebpf.Program `ebpf:"csm_on_exec"`
}

func (p *ExecPrograms) Close() error {
	return _ExecClose(
		p.CsmOnExec,
	)
}

func _ExecClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exec_x86_bpfel.o
var _ExecBytes []byte
