package privops

// operations is the inventory. Adding a subsystem that writes to the host, or
// a new grant in the systemd unit, means adding an entry here: internal/ci
// gates fail otherwise.
var operations = []Op{
	// --- Detection: reading the host ---
	{
		ID:               "detect.scan_account_files",
		Subsystem:        "detection",
		Summary:          "read every account's files for scheduled, real-time and on-demand scans",
		Privileges:       []Privilege{CapDACReadSearch, Root},
		Trigger:          Automatic,
		DisableKey:       "disabled_checks",
		DisableValue:     "name the checks to drop",
		WithoutPrivilege: "only files readable by CSM's own uid are scanned, which on a shared host is close to nothing",
	},
	{
		ID:               "detect.filesystem_events",
		Subsystem:        "detection",
		Summary:          "fanotify stream over account roots and world-writable temp directories",
		Privileges:       []Privilege{CapSysAdmin},
		Trigger:          Automatic,
		WithoutPrivilege: "no real-time file detection; scheduled scans still run, so a webshell lives until the next cycle",
	},
	{
		ID:               "detect.process_exec",
		Subsystem:        "detection",
		Summary:          "watch process execution through a BPF tracepoint, or by walking /proc",
		Privileges:       []Privilege{CapBPF, Root},
		Trigger:          Automatic,
		DisableKey:       "detection.exec_monitor_backend",
		DisableValue:     "none",
		WithoutPrivilege: "exec detection falls back to periodic /proc sampling and misses short-lived processes",
	},
	{
		ID:               "detect.outbound_connections",
		Subsystem:        "detection",
		Summary:          "watch outbound connections through BPF cgroup hooks, or by polling /proc/net/tcp",
		Privileges:       []Privilege{CapBPF, Root},
		Trigger:          Automatic,
		DisableKey:       "detection.connection_tracker_backend",
		DisableValue:     "none",
		WithoutPrivilege: "connection detection falls back to polling and misses short-lived connections",
	},
	{
		ID:               "detect.sensitive_file_writes",
		Subsystem:        "detection",
		Summary:          "watch writes to /etc/shadow and comparable files through a BPF LSM hook",
		Privileges:       []Privilege{CapBPF, Root},
		Trigger:          Automatic,
		DisableKey:       "detection.sensitive_files_backend",
		DisableValue:     "none",
		WithoutPrivilege: "sensitive-file changes are found by periodic hashing instead of at the moment of the write",
	},
	{
		ID:               "detect.af_alg_sockets",
		Subsystem:        "detection",
		Summary:          "watch AF_ALG socket use (CVE-2026-31431) through BPF LSM or the audit log",
		Privileges:       []Privilege{CapBPF, Root},
		Trigger:          Automatic,
		DisableKey:       "detection.af_alg_backend",
		DisableValue:     "none",
		WithoutPrivilege: "the live monitor is gone; the periodic critical check still reports an exposed kernel",
	},
	{
		ID:               "detect.read_service_logs",
		Subsystem:        "detection",
		Summary:          "read mail, authentication, web server and ModSecurity logs",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		WithoutPrivilege: "no mail abuse, brute-force or WAF detection: these logs are root-readable only",
	},
	{
		ID:               "detect.pam_events",
		Subsystem:        "detection",
		Summary:          "receive authentication attempts from the pam_csm.so hook over a private socket",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/run/csm"},
		WithoutPrivilege: "no immediate brute-force or credential-stuffing block; log parsing lags by up to a minute",
	},
	{
		ID:               "detect.account_databases",
		Subsystem:        "detection",
		Summary:          "read account MySQL credentials and scan databases for injected content and stored objects",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		DisableKey:       "detection.db_object_scanning",
		DisableValue:     "false",
		WithoutPrivilege: "no database detection: injected admin users, poisoned options and malicious triggers stay invisible",
	},
	{
		ID:               "detect.mail_queue_probe",
		Subsystem:        "detection",
		Summary:          "query the Exim queue through a transient unit, because Exim opens its logs even to answer a read",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Unsandboxed:      true,
		WithoutPrivilege: "queue composition and freeze targets are unknown, so mail abuse is detected later and less precisely",
	},
	{
		ID:               "detect.kernel_livepatch_probe",
		Subsystem:        "detection",
		Summary:          "run kcarectl --patch-info to see whether a KernelCare livepatch covers Copy Fail; kcarectl rewrites its own cache on every run",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/cache/kcare"},
		DisableKey:       "disabled_checks",
		DisableValue:     "af_alg_copy_fail",
		WithoutPrivilege: "a patched kernel reads as vulnerable, so the AF_ALG finding cannot be cleared",
	},

	// --- CSM's own state ---
	{
		ID:               "state.write_store",
		Subsystem:        "csm state",
		Summary:          "write the bbolt state database, baselines, incidents and scan reports",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/lib/csm", "/opt/csm/state"},
		WithoutPrivilege: "CSM cannot run: without state there is no baseline, no dedup and no incident history",
	},
	{
		ID:               "state.write_logs",
		Subsystem:        "csm state",
		Summary:          "write the daemon log and the audit-log sinks that feed a SIEM",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/log/csm"},
		WithoutPrivilege: "no local record of findings or actions",
	},
	{
		ID:               "state.sign_config",
		Subsystem:        "csm state",
		Summary:          "rewrite CSM's own integrity hashes into csm.yaml after an approved change",
		Privileges:       []Privilege{Root},
		Trigger:          Operator,
		Writes:           []string{"/etc/csm"},
		WithoutPrivilege: "the integrity gate cannot be re-signed, so the next restart refuses to start after any config edit",
	},
	{
		ID:               "state.update_signatures",
		Subsystem:        "csm state",
		Summary:          "download and signature-verify malware rule updates",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/opt/csm/rules"},
		DisableKey:       "signatures.auto_update",
		DisableValue:     "false",
		WithoutPrivilege: "detection freezes at the ruleset shipped with the installed package",
	},
	{
		ID:               "state.mail_relay_policies",
		Subsystem:        "csm state",
		Summary:          "keep per-account sending baselines used by the PHP-relay detector",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/opt/csm/policies"},
		DisableKey:       "email_protection.php_relay.enabled",
		DisableValue:     "false",
		WithoutPrivilege: "mail abuse is judged on absolute thresholds only, which is noisier on busy accounts",
	},
	{
		ID:               "state.php_shield_events",
		Subsystem:        "csm state",
		Summary:          "read and rotate the PHP Shield event log written by the PHP runtime hook",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/log/csm-php-shield"},
		DisableKey:       "php_shield.enabled",
		DisableValue:     "false",
		WithoutPrivilege: "PHP runtime events are not collected",
	},
	{
		ID:               "state.write_deploy_script",
		Subsystem:        "csm state",
		Summary:          "refresh the embedded upgrade script in CSM's own directory at startup",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/opt/csm/deploy.sh"},
		DisableKey:       "mode",
		DisableValue:     "observe",
		WithoutPrivilege: "the packaged upgrade helper is missing and upgrades are run by hand",
	},

	// --- Automatic response ---
	{
		ID:               "respond.quarantine_file",
		Subsystem:        "response",
		Summary:          "move a confirmed malicious file out of an account tree into CSM's quarantine, preserving owner, permissions and mtime",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/home", "/tmp", "/var/tmp", "/dev/shm", "/opt/csm/quarantine"},
		DisableKey:       "auto_response.quarantine_files",
		DisableValue:     "false",
		WithoutPrivilege: "malware is reported and left in place",
	},
	{
		ID:               "respond.clean_file",
		Subsystem:        "response",
		Summary:          "strip injected code from a PHP or access file, keeping a pre-clean backup",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/home", "/opt/csm/quarantine"},
		DisableKey:       "auto_response.clean_htaccess",
		DisableValue:     "false",
		WithoutPrivilege: "injected files are reported and left in place",
	},
	{
		ID:               "respond.kill_process",
		Subsystem:        "response",
		Summary:          "signal a malicious process through a kernel process handle, never a recycled PID, never root",
		Privileges:       []Privilege{CapKill, Root},
		Trigger:          Automatic,
		Writes:           []string{"process:signal"},
		DisableKey:       "auto_response.kill_processes",
		DisableValue:     "false",
		WithoutPrivilege: "reverse shells and miners keep running until an operator kills them",
	},
	{
		ID:               "respond.block_ip",
		Subsystem:        "response",
		Summary:          "add an attacker address or subnet to the firewall's deny sets",
		Privileges:       []Privilege{CapNetAdmin, Root},
		Trigger:          Automatic,
		Writes:           []string{"nftables:csm sets"},
		DisableKey:       "auto_response.block_ips",
		DisableValue:     "false",
		WithoutPrivilege: "attacks are reported but not stopped; dry-run records what would have been blocked",
	},
	{
		ID:               "respond.virtual_patch",
		Subsystem:        "response",
		Summary:          "write a reversible deny rule into an account access file to close an exposed file",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/home"},
		DisableKey:       "auto_response.virtual_patch_exposed_files",
		DisableValue:     "off",
		WithoutPrivilege: "exposed backups, dumps and configs stay reachable until the account owner fixes them",
	},
	{
		ID:               "respond.database_cleanup",
		Subsystem:        "response",
		Summary:          "revoke a rogue CMS admin, sanitize poisoned options, and drop confirmed malicious stored objects after recording their definition",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"mysql:account databases"},
		DisableKey:       "auto_response.clean_database",
		DisableValue:     "false",
		WithoutPrivilege: "database persistence survives file cleanup and re-infects the account",
	},
	{
		ID:               "respond.enforce_permissions",
		Subsystem:        "response",
		Summary:          "chmod a world-writable or group-writable PHP file back to 644",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/home"},
		DisableKey:       "auto_response.enforce_permissions",
		DisableValue:     "false",
		WithoutPrivilege: "writable code files are reported only",
	},
	{
		ID:               "respond.fix_wp_cron",
		Subsystem:        "response",
		Summary:          "disable WP-Cron for an account and install a per-user system cron entry instead",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/home", "/var/spool/cron"},
		DisableKey:       "auto_response.fix_wp_cron",
		DisableValue:     "false",
		WithoutPrivilege: "runaway WP-Cron load is reported only",
	},
	{
		ID:               "respond.freeze_mail",
		Subsystem:        "response",
		Summary:          "freeze queued Exim messages attributed to a confirmed PHP-relay finding",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/spool/exim/input", "/var/spool/exim4/input"},
		Unsandboxed:      true,
		DisableKey:       "auto_response.php_relay.freeze",
		DisableValue:     "false",
		WithoutPrivilege: "a compromised script keeps sending until an operator freezes the queue",
	},
	{
		ID:               "respond.quarantine_mail",
		Subsystem:        "response",
		Summary:          "move an infected message out of the Exim spool after an antivirus match",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/var/spool/exim/input", "/var/spool/exim4/input", "/opt/csm/quarantine"},
		DisableKey:       "email_av.quarantine_infected",
		DisableValue:     "false",
		WithoutPrivilege: "infected mail is reported and delivered",
	},
	{
		ID:               "respond.forward_guard",
		Subsystem:        "response",
		Summary:          "maintain the managed Exim block that holds forwarded spam and backscatter, and rebuild the Exim configuration",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"exim:configuration"},
		Unsandboxed:      true,
		DisableKey:       "email_protection.forward_guard.enabled",
		DisableValue:     "false",
		WithoutPrivilege: "forwarded spam keeps damaging the host's sending reputation",
	},
	{
		ID:               "respond.restart_mail_auth",
		Subsystem:        "response",
		Summary:          "restart the panel's mail authentication service after a sustained outage",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"service:mail authentication"},
		DisableKey:       "auto_response.mail_auth_recovery.restart_enabled",
		DisableValue:     "false",
		WithoutPrivilege: "an authentication backend outage is alerted but not repaired",
	},
	{
		ID:               "respond.af_alg_enforce",
		Subsystem:        "response",
		Summary:          "unload the AF_ALG kernel modules again when an opted-in mitigation marker is present",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"kernel:modules"},
		Unsandboxed:      true,
		DisableKey:       "auto_response.disable_enforce_af_alg",
		DisableValue:     "true",
		WithoutPrivilege: "a module reload silently reopens the Copy Fail exposure",
	},
	{
		ID:               "respond.bpf_deny_egress",
		Subsystem:        "response",
		Summary:          "deny matched outbound connections in the kernel through a BPF cgroup hook",
		Privileges:       []Privilege{CapBPF, Root},
		Trigger:          Automatic,
		Writes:           []string{"kernel:bpf cgroup program"},
		DisableKey:       "bpf_enforcement.enabled",
		DisableValue:     "false",
		WithoutPrivilege: "direct-to-MX spam egress is detected but not stopped at the source",
	},

	// --- Host integration ---
	{
		ID:               "integrate.firewall_ruleset",
		Subsystem:        "host integration",
		Summary:          "build and load CSM's nftables table, including the operator's port policy and rate limits",
		Privileges:       []Privilege{CapNetAdmin, Root},
		Trigger:          Automatic,
		Writes:           []string{"nftables:csm table"},
		DisableKey:       "firewall.enabled",
		DisableValue:     "false",
		WithoutPrivilege: "no firewall management; another tool owns the host's packet policy",
	},
	{
		ID:               "integrate.auditd_rules",
		Subsystem:        "host integration",
		Summary:          "write CSM's auditd rules and reload them, so audit-backed detection survives package upgrades",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/etc/audit"},
		DisableKey:       "mode",
		DisableValue:     "observe",
		WithoutPrivilege: "audit-backed detection layers stay inactive after an upgrade",
	},
	{
		ID:               "integrate.panel_plugin",
		Subsystem:        "host integration",
		Summary:          "deploy the WHM plugin CGI and its AppConfig entry, and register it with the panel",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/usr/local/cpanel/whostmgr/docroot/cgi", "/var/cpanel"},
		DisableKey:       "mode",
		DisableValue:     "observe",
		WithoutPrivilege: "no panel plugin; the web UI is still reachable on its own port",
	},
	{
		ID:               "integrate.modsec_section",
		Subsystem:        "host integration",
		Summary:          "rewrite CSM's marker-delimited section of the ModSecurity user configuration, preserving every byte outside it",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"/etc/apache2/conf.d", "/usr/local/apache/conf"},
		DisableKey:       "mode",
		DisableValue:     "observe",
		WithoutPrivilege: "CSM's virtual-patch WAF rules are not installed",
	},
	{
		ID:               "integrate.waf_vendor_rules",
		Subsystem:        "host integration",
		Summary:          "ask the panel to update stale ModSecurity vendor rulesets when a periodic check finds them out of date",
		Privileges:       []Privilege{Root},
		Trigger:          Automatic,
		Writes:           []string{"modsec:vendor rulesets"},
		DisableKey:       "mode",
		DisableValue:     "observe",
		WithoutPrivilege: "stale WAF rules are reported but not refreshed",
	},
	{
		ID:               "integrate.php_shield",
		Subsystem:        "host integration",
		Summary:          "install the PHP runtime hook and make its event directory visible inside account cages",
		Privileges:       []Privilege{Root},
		Trigger:          Operator,
		Writes:           []string{"php:runtime configuration", "cagefs:mounts"},
		DisableKey:       "php_shield.enabled",
		DisableValue:     "false",
		WithoutPrivilege: "no PHP runtime blocking of uploads and temp-directory execution",
	},
	{
		ID:           "integrate.challenge_snippet",
		Subsystem:    "host integration",
		Summary:      "refresh the web server snippet and rewrite maps that route challenged visitors to CSM's proof-of-work listener, and reload the web server when the snippet changed",
		Privileges:   []Privilege{Root},
		Trigger:      Automatic,
		DisableKey:   "mode",
		DisableValue: "observe",
		Writes: []string{
			"/etc/apache2/conf.d", "/etc/apache2/conf-enabled", "/etc/httpd/conf.d",
			"/etc/nginx/conf.d", "/usr/local/lsws/conf/templates", "/var/cache/csm",
		},
		WithoutPrivilege: "suspicious visitors are blocked outright instead of being offered a challenge",
	},

	// --- Operator commands ---
	{
		ID:               "operate.manual_remediation",
		Subsystem:        "operator commands",
		Summary:          "clean, quarantine or restore a named file, or drop a named database object, on request",
		Privileges:       []Privilege{Root},
		Trigger:          Operator,
		Writes:           []string{"/home", "/opt/csm/quarantine", "mysql:account databases"},
		WithoutPrivilege: "remediation is done by hand over SSH",
	},
	{
		ID:               "operate.manual_firewall",
		Subsystem:        "operator commands",
		Summary:          "block, allow, tempban or flush addresses on request, and roll a firewall apply back",
		Privileges:       []Privilege{CapNetAdmin, Root},
		Trigger:          Operator,
		Writes:           []string{"nftables:csm sets"},
		WithoutPrivilege: "firewall changes are made with nft or the panel's own tooling",
	},
	{
		ID:               "operate.truncate_error_log",
		Subsystem:        "operator commands",
		Summary:          "empty an account error log that has grown large enough to threaten the filesystem",
		Privileges:       []Privilege{Root},
		Trigger:          Operator,
		Writes:           []string{"/home"},
		WithoutPrivilege: "a bloated log is reported and truncated by hand",
	},
	{
		ID:               "operate.harden_host",
		Subsystem:        "operator commands",
		Summary:          "apply a supported CVE mitigation: a modprobe blacklist, or seccomp drop-ins for the services that need one",
		Privileges:       []Privilege{Root},
		Trigger:          Operator,
		Writes:           []string{"/etc/modprobe.d", "systemd:service drop-ins", "kernel:modules"},
		WithoutPrivilege: "the mitigation is applied by hand from the command the audit prints",
	},
	{
		ID:               "operate.install_service",
		Subsystem:        "operator commands",
		Summary:          "install or remove CSM itself: the systemd unit, the PAM hook, logrotate and the panel integrations",
		Privileges:       []Privilege{Root},
		Trigger:          Operator,
		Writes:           []string{"systemd:csm.service", "pam:configuration", "logrotate:configuration"},
		WithoutPrivilege: "CSM cannot be installed as a service",
	},
}
