//go:build linux

package daemon

import (
	"fmt"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/pidginhost/csm/internal/alert"
	"github.com/pidginhost/csm/internal/wpcheck"
)

// WordPress unpacks every core, plugin and theme package under
// wp-content/upgrade/<package>/<unpacked>/ and moves the unpacked tree into
// place a few hundred milliseconds later. The analyzer sees each staged PHP
// file in that window, usually before the checksum fetch for the package
// version has finished and sometimes before the header file that names the
// version has even been written.
//
// A staged file is therefore judged by hash, not by where it sits. Files the
// verifier can compare are compared; files whose checksums are still on the
// way wait here and are compared once they land, from the installed location
// if WordPress has moved them by then. Only a file that fails the comparison
// gets its own finding. Packages with no checksum source, and packages the
// fetch cannot resolve in time, collapse to one finding per staging directory.

// wpVerifier is the wordpress.org checksum verifier the analyzer consults.
type wpVerifier interface {
	Describe(path string) wpcheck.Verification
	Verify(v wpcheck.Verification) wpcheck.Verdict
	VerifyFile(fd int, path string) wpcheck.Verification
}

const (
	// stagedPackageTimeout bounds how long a staged file waits for its
	// package checksums. The fetch is one ZIP download; a package still
	// unresolved after this is reported at the directory level instead.
	stagedPackageTimeout = 60 * time.Second
	// stagedPackageQueueMax caps queued files across all packages. A full
	// core or plugin update is a few thousand files; the cap only matters
	// when many updates run at once while the fetches stall.
	stagedPackageQueueMax = 20000
	// stagedPackageIdleTTL retires per-package state that saw no new file.
	stagedPackageIdleTTL = 10 * time.Minute
	// wpPathNegativeTTL is how long a missing path stays cached. WordPress
	// moves the old plugin to upgrade-temp-backup/ and renames the new tree
	// in a few hundred milliseconds later, so a negative answer is transient
	// by definition and must not hold for the five minutes a positive one does.
	wpPathNegativeTTL = 2 * time.Second
)

// wpStagedPackage is a parsed wp-content/upgrade/<package>/<unpacked>/ path.
type wpStagedPackage struct {
	dir      string
	unpacked string
	wpRoot   string
}

// parseWPStagedPackage identifies the staging directory and the unpacked tree
// a path sits in. Pure string work: the staging name is generated by
// WordPress in several shapes and carries no authority anyway, since anything
// able to write a staged tree chooses both names.
func parseWPStagedPackage(path string) wpStagedPackage {
	const marker = "/wp-content/upgrade/"
	idx := strings.Index(path, marker)
	if idx < 0 {
		return wpStagedPackage{}
	}
	rest := path[idx+len(marker):]
	pkg, inner, ok := strings.Cut(rest, "/")
	if !ok || pkg == "" {
		return wpStagedPackage{} // a file sitting directly in upgrade/ belongs to no package
	}
	unpacked, _, ok := strings.Cut(inner, "/")
	if !ok || unpacked == "" {
		return wpStagedPackage{} // the package directory holds no unpacked tree
	}
	return wpStagedPackage{
		dir:      path[:idx+len(marker)] + pkg,
		unpacked: unpacked,
		wpRoot:   path[:idx],
	}
}

// wpPackageInstalled reports whether the unpacked tree names something the
// site already has: a plugin or theme directory, its rollback copy under
// upgrade-temp-backup/ while an update is mid-flight, or a WordPress root for
// a core package.
func wpPackageInstalled(wpRoot, unpacked string) bool {
	if unpacked == "wordpress" {
		return cachedPathExists(wpRoot + "/wp-includes/version.php")
	}
	for _, dir := range []string{
		"/wp-content/plugins/", "/wp-content/themes/",
		"/wp-content/upgrade-temp-backup/plugins/", "/wp-content/upgrade-temp-backup/themes/",
	} {
		if cachedPathExists(wpRoot + dir + unpacked) {
			return true
		}
	}
	return false
}

type stagedPackageFile struct {
	path     string
	procInfo string
	v        wpcheck.Verification
	pkg      wpStagedPackage
	queuedAt time.Time
}

// stagedPackageInfo is what the directory-level finding says about a package.
// installed is decided on the package's first file, while the old tree or its
// rollback copy is still on disk.
type stagedPackageInfo struct {
	installed bool
	kind      wpcheck.PackageKind
	slug      string
	version   string
	lastSeen  time.Time
}

type stagedPackageQueue struct {
	mu       sync.Mutex
	limit    int
	files    []stagedPackageFile
	packages map[string]stagedPackageInfo
}

func newStagedPackageQueue(limit int) *stagedPackageQueue {
	return &stagedPackageQueue{limit: limit, packages: make(map[string]stagedPackageInfo)}
}

func (q *stagedPackageQueue) pendingCount() int {
	q.mu.Lock()
	defer q.mu.Unlock()
	return len(q.files)
}

// note records a package the analyzer saw a file of and returns its info,
// resolving installed-ness on first sight and the identity as soon as a
// description carries one.
func (q *stagedPackageQueue) note(pkg wpStagedPackage, v wpcheck.Verification, now time.Time) stagedPackageInfo {
	q.mu.Lock()
	defer q.mu.Unlock()
	info, ok := q.packages[pkg.dir]
	if !ok {
		info.installed = wpPackageInstalled(pkg.wpRoot, pkg.unpacked)
	}
	if v.Kind != wpcheck.KindNone {
		info.kind = v.Kind
	}
	if v.Slug != "" {
		info.slug = v.Slug
	}
	if v.Version != "" {
		info.version = v.Version
	}
	info.lastSeen = now
	q.packages[pkg.dir] = info
	return info
}

func (q *stagedPackageQueue) info(dir string) stagedPackageInfo {
	q.mu.Lock()
	defer q.mu.Unlock()
	return q.packages[dir]
}

func (q *stagedPackageQueue) push(f stagedPackageFile) bool {
	q.mu.Lock()
	defer q.mu.Unlock()
	if len(q.files) >= q.limit {
		return false
	}
	q.files = append(q.files, f)
	return true
}

// take hands every queued file to the caller, which requeues the ones still
// waiting. Files queued while a drain runs are appended after them.
func (q *stagedPackageQueue) take() []stagedPackageFile {
	q.mu.Lock()
	defer q.mu.Unlock()
	files := q.files
	q.files = nil
	return files
}

func (q *stagedPackageQueue) requeue(files []stagedPackageFile) {
	if len(files) == 0 {
		return
	}
	q.mu.Lock()
	defer q.mu.Unlock()
	q.files = append(files, q.files...)
}

func (q *stagedPackageQueue) evictIdle(now time.Time) {
	q.mu.Lock()
	defer q.mu.Unlock()
	for dir, info := range q.packages {
		if now.Sub(info.lastSeen) > stagedPackageIdleTTL {
			delete(q.packages, dir)
		}
	}
}

func (fm *FileMonitor) stagedPackages() *stagedPackageQueue {
	fm.wpPendingInit.Do(func() {
		if fm.wpPending == nil {
			fm.wpPending = newStagedPackageQueue(stagedPackageQueueMax)
		}
	})
	return fm.wpPending
}

// handleStagedPackageFile takes over a content-clean PHP file written inside
// a staged package. It returns false when path is not inside one, so the
// caller keeps its per-file warning for loose files under upgrade/.
func (fm *FileMonitor) handleStagedPackageFile(path string, v wpcheck.Verification, procInfo string) bool {
	pkg := parseWPStagedPackage(path)
	if pkg.dir == "" {
		return false
	}
	now := time.Now()
	q := fm.stagedPackages()
	info := q.note(pkg, v, now)

	switch v.Verdict {
	case wpcheck.VerdictMismatch, wpcheck.VerdictUnverifiable:
		fm.alertStagedFileMismatch(path, pkg, v, procInfo)
	case wpcheck.VerdictPending, wpcheck.VerdictNoVersion, wpcheck.VerdictReady:
		if !q.push(stagedPackageFile{path: path, procInfo: procInfo, v: v, pkg: pkg, queuedAt: now}) {
			fm.alertStagedPackage(pkg, info, "verification queue full", procInfo)
		}
	default:
		fm.alertStagedPackage(pkg, info, stagedPackageReason(v), procInfo)
	}
	return true
}

func stagedPackageReason(v wpcheck.Verification) string {
	switch {
	case v.Verdict == wpcheck.VerdictUnavailable && v.Kind == wpcheck.KindTheme:
		return "themes have no checksum source"
	case v.Verdict == wpcheck.VerdictUnavailable:
		return "not published on wordpress.org"
	}
	return "no plugin, theme or core header found"
}

func stagedPackageWhat(info stagedPackageInfo, pkg wpStagedPackage) string {
	name := info.slug
	if name == "" {
		name = pkg.unpacked
	}
	var what string
	switch info.kind {
	case wpcheck.KindCore:
		what = "WordPress core"
	case wpcheck.KindPlugin:
		what = "plugin " + name
	case wpcheck.KindTheme:
		what = "theme " + name
	default:
		what = "package " + name
	}
	if info.version != "" {
		what += " " + info.version
	}
	return what
}

// alertStagedPackage raises the one directory-level finding for a package
// that cannot be verified file by file. Dedup is keyed on the directory, so
// every file of the package lands on the same finding.
func (fm *FileMonitor) alertStagedPackage(pkg wpStagedPackage, info stagedPackageInfo, reason, procInfo string) {
	what := stagedPackageWhat(info, pkg)
	state := "new install"
	if info.installed {
		state = "updates installed " + strings.TrimSuffix(what, " "+info.version)
	}
	fm.sendAlertWithPath(alert.Warning, "php_in_sensitive_dir_realtime",
		fmt.Sprintf("WordPress package staged, not verified against wordpress.org: %s", pkg.dir),
		fmt.Sprintf("%s; %s; %s. Every staged file was content-scanned and none was flagged.", what, state, reason),
		pkg.dir, procInfo)
}

// stagedFileInstalledPath is where WordPress puts a staged file once the
// package is moved into place.
func stagedFileInstalledPath(pkg wpStagedPackage, v wpcheck.Verification) string {
	if v.Rel == "" {
		return ""
	}
	switch v.Kind {
	case wpcheck.KindPlugin:
		if v.Slug == "" {
			return ""
		}
		return pkg.wpRoot + "/wp-content/plugins/" + v.Slug + "/" + v.Rel
	case wpcheck.KindCore:
		return pkg.wpRoot + "/" + v.Rel
	}
	return ""
}

func pathPresent(path string) bool {
	_, err := os.Lstat(path)
	return err == nil
}

// alertStagedFileMismatch raises the per-file finding for a staged file that
// is not what the official package ships. If WordPress has already moved the
// tree, the finding names the installed path so it can be acted on there.
func (fm *FileMonitor) alertStagedFileMismatch(stagedPath string, pkg wpStagedPackage, v wpcheck.Verification, procInfo string) {
	reportPath := stagedPath
	moved := false
	if !pathPresent(stagedPath) {
		if installed := stagedFileInstalledPath(pkg, v); installed != "" && pathPresent(installed) {
			reportPath, moved = installed, true
		}
	}
	what := v.Slug + " " + v.Version
	if v.Kind == wpcheck.KindCore {
		what = "WordPress " + v.Version
	}
	message := fmt.Sprintf("Staged file does not match wordpress.org %s: %s", what, reportPath)
	details := "Content rules found nothing. The file differs from the official package or is not part of it."
	if v.Verdict == wpcheck.VerdictUnverifiable {
		message = fmt.Sprintf("Staged file could not be verified against wordpress.org %s: %s", what, reportPath)
		details = "Content rules found nothing. The file is larger than the hash size cap, so the official checksum could not be compared."
	}
	if moved {
		details += fmt.Sprintf(" Staged at %s, since installed.", stagedPath)
	}
	fm.sendAlertWithPath(alert.Warning, "php_in_sensitive_dir_realtime", message, details, reportPath, procInfo)
}

// redescribeStaged retries identifying a file queued before its package
// header existed, from the staged path and then from the installed one.
// The digest taken at event time is kept: a rename does not change content,
// and a later write is a new event.
func (fm *FileMonitor) redescribeStaged(f stagedPackageFile) wpcheck.Verification {
	unresolved := func(v wpcheck.Verification) bool {
		return v.Verdict == wpcheck.VerdictNoVersion || v.Verdict == wpcheck.VerdictUnknown
	}
	v := fm.wpCache.Describe(f.path)
	if unresolved(v) {
		if installed := stagedFileInstalledPath(f.pkg, f.v); installed != "" && pathPresent(installed) {
			if iv := fm.wpCache.Describe(installed); !unresolved(iv) {
				v = iv
			}
		}
	}
	if unresolved(v) {
		return f.v
	}
	v.Digest = f.v.Digest
	return v
}

// drainStagedPackages resolves every queued file whose checksums have
// arrived and reports packages that ran out of time.
func (fm *FileMonitor) drainStagedPackages(now time.Time) {
	q := fm.stagedPackages()
	q.evictIdle(now)
	files := q.take()
	if len(files) == 0 {
		return
	}
	var keep []stagedPackageFile
	for _, f := range files {
		v := f.v
		if v.Verdict == wpcheck.VerdictNoVersion || v.Version == "" {
			v = fm.redescribeStaged(f)
			q.note(f.pkg, v, now)
		}
		verdict := v.Verdict
		if verdict == wpcheck.VerdictPending || verdict == wpcheck.VerdictReady {
			verdict = fm.wpCache.Verify(v)
		}
		switch verdict {
		case wpcheck.VerdictVerified:
		case wpcheck.VerdictMismatch, wpcheck.VerdictUnverifiable:
			v.Verdict = verdict
			fm.alertStagedFileMismatch(f.path, f.pkg, v, f.procInfo)
		case wpcheck.VerdictPending, wpcheck.VerdictNoVersion, wpcheck.VerdictReady:
			if now.Sub(f.queuedAt) > stagedPackageTimeout {
				fm.alertStagedPackage(f.pkg, q.info(f.pkg.dir),
					fmt.Sprintf("checksums not fetched within %s", stagedPackageTimeout), f.procInfo)
				continue
			}
			f.v = v
			keep = append(keep, f)
		default:
			fm.alertStagedPackage(f.pkg, q.info(f.pkg.dir), stagedPackageReason(v), f.procInfo)
		}
	}
	q.requeue(keep)
}

// stagedPackageLoop drains the queue once a second until the monitor stops.
func (fm *FileMonitor) stagedPackageLoop() {
	defer fm.wg.Done()
	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-fm.stopCh:
			return
		case now := <-ticker.C:
			fm.drainStagedPackages(now)
		}
	}
}
